CREATE TABLE CATEGORY(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
id_parent INT(11),
CONSTRAINT FOREIGN KEY(ID_PARENT) REFERENCES CATEGORY(ID)
);

CREATE TABLE PRODUCT(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
price FLOAT,
quality INT(11),
image VARCHAR(255),
status BIT DEFAULT 0,
discount INT(3),
description VARCHAR(255),
id_cate INT(11),
CONSTRAINT FOREIGN KEY(ID_CATE) REFERENCES CATEGORY(ID)
);

CREATE TABLE IMAGE_PRODUCT(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
id_product INT(11),
CONSTRAINT FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE CART(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
address VARCHAR(255),
phone VARCHAR(255),
status BIT DEFAULT 0,
create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
success_at DATETIME
);
s
CREATE TABLE CART_DETAILS(
id_cart INT(11),
id_product INT(11),
quality INT(11),
PRIMARY KEY(ID_CART, ID_PRODUCT),
CONSTRAINT FOREIGN KEY(id_cart) REFERENCES CART(id),
CONSTRAINT FOREIGN KEY(id_product) REFERENCES PRODUCT(id)
);

CREATE TABLE USER(
username VARCHAR(255) PRIMARY KEY,
password VARCHAR(255),
name VARCHAR(255),
address VARCHAR(255),
craete_at DATETIME DEFAULT CURRENT_TIMESTAMP,
status BIT DEFAULT 1
);